# Generated by Django 5.0.1 on 2024-02-06 17:11

from django.db import migrations, models

import core.services.upload_photo


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_options_carmodel_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to=core.services.upload_photo.upload_photo),
        ),
    ]
