# Generated by Django 5.0.1 on 2024-02-06 17:11

from django.db import migrations, models

import core.services.upload_avatar


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.services.upload_avatar.upload_avatar),
        ),
    ]
