# Generated by Django 5.0.1 on 2024-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('cabin_type', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('count_of_saddles', models.IntegerField()),
                ('engine_type', models.FloatField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
